### ISSUE TITLE
Chrome returning a 406 Not Acceptable response

### ISSUE THREAD

**Issue by drewrawitz** [AgilionApps/ja_serializer#138] opened 2016-07-15 15:40 UTC
Hello,

I started a brand new phoenix project and followed these docs but I keep running into a weird issue.  Chrome is returning a 406 error:

![](https://api.monosnap.com/rpc/file/download?id=xaVWRjQtP9tRe3h6p1VeHQaHGXhLmB)

However, if I run that same URL into Postman, I get a valid response!

![](https://api.monosnap.com/rpc/file/download?id=4jidpKLpb6w31lu9t3IUbEBn16bind)

Have you seen this before?  The steps I took were:

* Create a brand new phoenix project
* Install JaSerializer 0.9.0
* Added the following to `config.exs`
```
config :phoenix, :format_encoders,
  "json-api": Poison

config :plug, :mimes, %{
  "application/vnd.api+json" => ["json-api"]
}
```
* Added json-api to my plug pipeline
```
pipeline :api do
  plug :accepts, ["json-api"]
  plug JaSerializer.ContentTypeNegotiation
  plug JaSerializer.Deserializer
end
```
* Used the JSON API Generator
```
mix ja_serializer.gen.phoenix_api User users first_name:string last_name:string username:string email:string bio:text
```

I think that was it, did I miss anything? It's weird that it works fine in Postman.  Sorry if I missed out any important details, let me know if you need me to specify anything else.

Thank you!

**Comment by alanpeabody** [comment] 2016-07-15 16:19
Are you hitting this url directly in chrome? Or via an ajax request?

My guess is just that it doesn't have an acceptable "Accept" header. `*/*`, `application/*`, and `application/vnd.api+json` should work. Postman is probably sending one of those where as chrome is not.

Going to close this, but if the problem persists or you believe this is a bug please don't hesitate to reopen this!

**Closed by alanpeabody** 2016-07-15 16:19 UTC

**Comment by drewrawitz** [comment] 2016-07-15 16:22
@alanpeabody Thanks for your quick reply. I'm hitting the URL directly in chrome.  That should be fine, right?  

Is there anything I can do in the code to make it work?

**Comment by alanpeabody** [comment] 2016-07-15 16:33
My understanding of the spec is that this behavior is correct, but I might be mis-interpreting it:

http://jsonapi.org/format/#content-negotiation

Basically your browser is not sending the right "Accept" header for JSON-API. You could remove the ContentTypeNegotiation plug, but you would probably end up running into other problems or reproducing it. You could also use an api tool that sends an acceptable Accept header, such as postman, curl, etc.

**Comment by drewrawitz** [comment] 2016-07-15 16:48
Hmm, interesting. Removing `plug JaSerializer.ContentTypeNegotiation` did seem to work.  It sounds like that should be left in there, though. 

I'll keep digging.. let me know if you have any other ideas. Thanks!

**Comment by drewrawitz** [comment] 2016-07-15 17:16
Weird, so I added some headers to my request in Postman.

`Accept */*` returned a **200**
`Accept application/*` returned a **406**
`Accept application/vnd.api+json` returned a **406**

**Comment by alanpeabody** [comment] 2016-07-15 17:37
After adding that to your config did you touch and recompile? (And do you still have the ContentTypeNegotiation plug?)

touch deps/plug/mix.exs
mix deps.compile plug

**Comment by drewrawitz** [comment] 2016-07-15 17:39
@alanpeabody Yep, I did the touch and recompile. Still the same error. 

Yeah I added back in the ContentTypeNegotiation plug.

**Comment by coryodaniel** [comment] 2016-08-04 19:04
What version of Phoenix are you using? I had the same issue, turns out "mimes" is no longer the key name in config.exs... try:

```elixir
config :plug, :types, %{
  "application/vnd.api+json" => ["json-api"]
}

```

**Comment by xn4v8h** [comment] 2016-09-09 07:20
moved to `config :mime, :types`, still having an issue :/

**Comment by xn4v8h** [comment] 2016-09-09 07:26
perhaps related: https://github.com/phoenixframework/phoenix/issues/1879#issuecomment-242976787

**Comment by alanpeabody** [comment] 2016-09-09 12:45
@xn4v8h can you please open a new issue with the exact problem you are having? There are a couple of different problems in this thread, all of which have been addressed by this or with updates to install instructions etc
